(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_.,x_Symbol] :=
  (b/2+c*x)^(2*p+1)/(c^(p+1)*(2*p+1)) /;
FreeQ[{a,b,c},x] && EqQ[b^2-4*a*c,0] && IntegerQ[p]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (a+b*x+c*x^2)^FracPart[p]/(c^IntPart[p]*(b/2+c*x)^(2*FracPart[p])) \[Star] Int[(b/2+c*x)^(2*p),x] /;
FreeQ[{a,b,c,p},x] && EqQ[b^2-4*a*c,0] && Not[IntegerQ[p]]


(* ::Code:: *)
Int[(b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[x^p*(b+c*x)^p,x],x] /;
FreeQ[{b,c},x] && IntegerQ[p]


(* ::Code:: *)
Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  2*c/q \[Star] Int[1/(b-q+2*c*x),x] - 2*c/q \[Star] Int[1/(b+q+2*c*x),x]] /;
FreeQ[{a,b,c},x] && NiceSqrtQ[b^2-4*a*c]


(* ::Code:: *)
Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  With[{q=1-4*Simplify[a*c/b^2]},
  -2/b \[Star] Subst[Int[1/(q-x^2),x],x,1+2*c*x/b] /;
 RationalQ[q] && (EqQ[q^2,1] || Not[RationalQ[b^2-4*a*c]])] /;
FreeQ[{a,b,c},x]


(* ::Code:: *)
Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  -2 \[Star] Subst[Int[1/(Simplify[b^2-4*a*c]-x^2),x],x,b+2*c*x] /;
FreeQ[{a,b,c},x]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  1/c^p \[Star] Int[ExpandIntegrand[(b/2-q/2+c*x)^p*(b/2+q/2+c*x)^p,x],x] /;
 Not[FractionalPowerFactorQ[q]]] /;
FreeQ[{a,b,c},x] && IntegerQ[p] && NiceSqrtQ[b^2-4*a*c]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(a+b*x+c*x^2)^p,x],x] /;
FreeQ[{a,b,c},x] && IGtQ[p,0]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b+2*c*x)*(a+b*x+c*x^2)^(p+1)/((p+1)*(b^2-4*a*c)) -
  2*c*(2*p+3)/((p+1)*(b^2-4*a*c)) \[Star] Int[(a+b*x+c*x^2)^(p+1),x] /;
FreeQ[{a,b,c},x] && ILtQ[p,-1]


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b+2*c*x)*(a+b*x+c*x^2)^p/(2*c*(2*p+1)) -
  p*(b^2-4*a*c)/(2*c*(2*p+1)) \[Star] Int[(a+b*x+c*x^2)^(p-1),x] /;
FreeQ[{a,b,c},x] && GtQ[p,0] && (IntegerQ[4*p] || IntegerQ[3*p])


(* ::Code:: *)
Int[1/(a_.+b_.*x_+c_.*x_^2)^(3/2),x_Symbol] :=
  -2*(b+2*c*x)/((b^2-4*a*c)*Sqrt[a+b*x+c*x^2]) /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0]


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b+2*c*x)*(a+b*x+c*x^2)^(p+1)/((p+1)*(b^2-4*a*c)) -
  2*c*(2*p+3)/((p+1)*(b^2-4*a*c)) \[Star] Int[(a+b*x+c*x^2)^(p+1),x] /;
FreeQ[{a,b,c},x] && LtQ[p,-1] && (IntegerQ[4*p] || IntegerQ[3*p])


(* ::Code:: *)
Int[(b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  1/(2^(2*p+1)*c*(-c/(b^2))^p) \[Star] Subst[Int[(1-x^2/b^2)^p,x],x,b+2*c*x] /;
FreeQ[{b,c,p},x] && LtQ[b^2/c,0]


(* ::Code:: *)
Int[1/Sqrt[b_.*x_+c_.*x_^2],x_Symbol] :=
  2 \[Star] Subst[Int[1/(1-c*x^2),x],x,x/Sqrt[b*x+c*x^2]] /;
FreeQ[{b,c},x]


(* ::Code:: *)
Int[(b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b*x+c*x^2)^p/(-c*(b*x+c*x^2)/(b^2))^p \[Star] Int[(-c*x/b-c^2*x^2/b^2)^p,x] /;
FreeQ[{b,c},x] && (IntegerQ[4*p] || IntegerQ[3*p])


(* ::Code:: *)
Int[(b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  -(b*x+c*x^2)^(p+1)/(b*(p+1)*(-c*x/b)^(p+1))*Hypergeometric2F1[-p,p+1,p+2,1+c*x/b] /;
FreeQ[{b,c,p},x] && Not[IntegerQ[4*p]] && Not[IntegerQ[3*p]]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{q=Simplify[b^2-4*a*c]},
  1/(2^(2*p+1)*c*(-c/q)^p) \[Star] Subst[Int[(1-x^2/q)^p,x],x,b+2*c*x] /;
 LtQ[c/q,0]] /;
FreeQ[{a,b,c,p},x]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_+c_.*x_^2],x_Symbol] :=
  2 \[Star] Subst[Int[1/(4*c-x^2),x],x,(b+2*c*x)/Sqrt[a+b*x+c*x^2]] /;
FreeQ[{a,b,c},x]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{k=Denominator[p]},
  k*Sqrt[(b+2*c*x)^2]/(b+2*c*x) \[Star] Subst[Int[x^(k*(p+1)-1)/Sqrt[b^2-4*a*c+4*c*x^k],x],x,(a+b*x+c*x^2)^(1/k)]] /;
FreeQ[{a,b,c},x] && (IntegerQ[4*p] || IntegerQ[3*p])


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  -(a+b*x+c*x^2)^(p+1)/(q*(p+1)*((q-b-2*c*x)/(2*q))^(p+1))*Hypergeometric2F1[-p,p+1,p+2,(b+q+2*c*x)/(2*q)]] /;
FreeQ[{a,b,c,p},x] && Not[IntegerQ[4*p]] && Not[IntegerQ[3*p]]



